# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  compose:up:
    desc: "run docker containers"
    cmd: docker compose up -d

  compose:down:
    desc: "stop running docker containers"
    cmd: docker compose down

  db:cli:
    desc: "access db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -d {{ .DB_NAME }}

  dev:
    desc: "run go backend api in dev mode"
    cmd: air
